### Generated by CMS system ###

install
key --skip
lang en_US.UTF-8
keyboard us

network --device eth0 --onboot yes --bootproto static  --ip 10.122.76.244 --netmask 255.255.255.0 --hostname cn10proadbe01
network --device eth1 --onboot yes --bootproto static  --ip 10.86.233.71 --netmask 255.255.255.0 --gateway 10.86.233.250 --hostname cn10proadbe01 --nameserver 10.86.235.10
rootpw --iscrypted $1$gLiElLLF$mZzYcEhsCF0mQeeldpqdP0
firewall --disabled
##  authconfig --enableshadow --enablemd5
selinux --disabled
timezone --utc UTC
firstboot --disable
skipx
text
bootloader --location=mbr --md5pass=$1$0c3AY0$bijoy3wmgdy3NnATIa/VV1
zerombr

part / --fstype=ext3 --size=8192 --asprimary --onpart=xvda1
part /home --fstype=ext3 --size=10240 --onpart=xvda3
part /var --fstype=ext3 --size=8192 --onpart=xvda5
part swap --size=4096 --asprimary --onpart=xvda2
part /u01 --fstype=ext3 --size=200 --noformat --onpart=xvde1 --grow

reboot

######install set of software

%packages --nobase
-anacron
-hal
-kudzu
-pm-utils
-prelink
audit
sysstat
vim-enhanced
mc
man
groff
wget
ntp
mlocate
dhclient
openssh
openssh-clients
openssh-server
postfix
vim-minimal
crontabs
anacron
vixie-cron
telnet
yum
bzip2
unzip
sudo
mailx
pciutils
dmidecode
coreutils
iproute
gdb
lsof
net-tools
procps
psmisc
pstack
rpm
strace
sysstat
tcpdump
util-linux
patch
iptables
-sysklogd
rsyslog
yum-utils
net-snmp
   

%post
(
#detect some virtual machines

[ -d /proc/xen ] && { grep -q "control_d" /proc/xen/capabilities || VIRTUAL="XEN-DOMU"; }
lspci -n | grep -q "5853:0001" && VIRTUAL="XEN-HVM"
lspci -n | grep -q "15ad:0405" && VIRTUAL="VMWARE"
lspci -n | grep -q "80ee:beef" && VIRTUAL="VIRTUALBOX"
lspci -n | grep -q "80ee:cafe" && VIRTUAL="VIRTUALBOX"
lspci -n | grep -q "1af4:1002" && VIRTUAL="KVM"

# bonds


# routes (before configuring network!)

echo -e "ADDRESS0=10.86.232.0\nNETMASK0=255.255.252.0\nGATEWAY0=10.86.233.250" >> /etc/sysconfig/network-scripts/route-eth1
echo "Restarting networking..." && service network restart 1>/dev/null


#DNS settings
cat << EOF > /etc/resolv.conf
options attempts:1 timeout:1 rotate
nameserver 10.122.76.252
nameserver 10.86.235.10
nameserver 10.86.233.3
domain cn10.phorm.com
search cn10.phorm.com
EOF

### creating new /etc/hosts
cat << EOF > /etc/hosts
# Do not remove the following line, or various programs
# that require network functionality will fail
127.0.0.1               localhost.localdomain localhost
::1             localhost6.localdomain6 localhost6
EOF

### set time
[ "$VIRTUAL" = "XEN-DOMU" ] && { echo 1 > /proc/sys/xen/independent_wallclock; }

/usr/sbin/ntpdate -b ntp1
# ntp.conf
mv /etc/ntp.conf /etc/ntp.conf.orig
cat << EOF > /etc/ntp.conf
restrict default kod nomodify notrap nopeer noquery
restrict 127.0.0.1
server ntp1
server ntp2
driftfile /var/lib/ntp/drift
keys /etc/ntp/keys
EOF

# core dumps

### SECURITY

## Security notice that will be printed after a successful login
echo '+---------------------------------------------------+
| WARNING:                                          |
|                                                   |
| You have accessed a server operated by Phorm.     |
|                                                   |
| You must be personally authorised by the system   |
| administrator before you use this computer and    |
| you are strictly limited to the extent of that    |
| authorisation. Unauthorised access or misuse of   |
| this computer is prohibited and may constitute    |
| an offence under the Computer Misuse Act 1990.    |
|                                                   |
| If you are not authorised to use this system,     |
| terminate this session immediately. Please note   |
| that all access is logged.                        |
+---------------------------------------------------+

' >> /etc/motd

## Editing sysctl
cat << EOF >> /etc/sysctl.conf
# security settings
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.tcp_max_syn_backlog = 4096
EOF


## Force password login for single user mode
echo 'su:S:wait:/sbin/sulogin' >> /etc/inittab
## Disallow ctrl-alt-del from console
sed -i 's|^ca::ctrlaltdel:/sbin/shutdown -t3 -r now|#&|' /etc/inittab


## Set the minimum password length to 8 chars
sed -i 's|PASS_MIN_LEN  5|PASS_MIN_LEN  8|' /etc/login.defs

cat << EOF >> /etc/profile
## Set bash to logout after 30 minutes
TMOUT=1800

## The screen should be cleared on logout
trap clear 0
EOF

## SSH configuration settings
sed 's|PasswordAuthentication yes|PasswordAuthentication no|g' -i /etc/ssh/sshd_config

cat << EOF >> /etc/ssh/sshd_config
Port 22
LogLevel VERBOSE
PermitRootLogin no
RhostsRSAAuthentication no
HostbasedAuthentication no
IgnoreRhosts yes
PermitEmptyPasswords no
EOF

## Enabling sysstat
chkconfig sysstat on


## Setting umask to 077
for i in /etc/{profile,bashrc,csh.cshrc,login.defs,csh.login} `find /etc/profile.d/ | xargs echo` /root/{.bashrc,.bash_profile,.cshrc,.tcshrc}
do
[ -f "$i" ] && sed s'|^\(\s*umask\s\+\)[0-9]\{3\}\(.*\)$|\1077\2|i' -i $i
done

## specifying coredumps dir and files
[ -d '/u01/cores' ] || mkdir -p -m 1777 /u01/cores
echo 'kernel.core_pattern = /u01/cores/%e-%p' >> /etc/sysctl.conf
############END OF SECURITY


## grub.conf
sed -i 's|^splashimage|#&|; s|^hiddenmenu|#&|; s|\(.*/vmlinuz-.*\)|\1 vga=791|; s| rhgb | |; s| quiet | |;' /boot/grub/grub.conf


# console configuration
[ "$VIRTUAL" = "XEN-DOMU" ] && { echo 'co:2345:respawn:/sbin/agetty xvc0 9600 vt100-nav' >> /etc/inittab; }
#[ "$VIRTUAL" = "KVM" ] && { echo 'S0:2345:respawn:/sbin/agetty ttyS0 115200 vt100-nav' >> /etc/inittab; echo "ttyS0" >> /etc/securetty; }
[ "$VIRTUAL" = "KVM" ] && { echo "ttyS0" >> /etc/securetty; }

# disable 169.254.0.0/16 subnet
echo 'NOZEROCONF=yes' >> /etc/sysconfig/network

# disable ipv6
grep -q 'NETWORKING_IPV6' /etc/sysconfig/network || echo 'NETWORKING_IPV6=no' >> /etc/sysconfig/network
sed 's|NETWORKING_IPV6=yes|NETWORKING_IPV6=no|' -i /etc/sysconfig/network
#echo -e '\n## Disable ipv6\nalias net-pf-10 off\nalias ipv6 off\ninstall ipv6 /bin/true' >> /etc/modprobe.d/disable-ipv6.conf

echo -e "# Disable ipv6\noptions ipv6 disable=1" >> /etc/modprobe.d/disable-ipv6.conf

# tune postfix
sed -e 's|inet_protocols.*|inet_protocols = ipv4|' -e \
'1,/^#myhostname =.*/s/^#myhostname =.*/myhostname = cn10proadbe01.cn10.phorm.com\n&/' \
-i /etc/postfix/main.cf

echo -e '#Bug 564274 - fake EDAC errors\nblacklist i3200_edac' >> /etc/modprobe.d/blacklist-edac.conf



### /etc/sysctl.conf
cat << EOF >> /etc/sysctl.conf
# Prevent arp answer on wrong interface
net.ipv4.conf.all.arp_filter = 1
net.ipv4.conf.all.arp_ignore = 2
# disable ipv6
net.ipv6.conf.all.disable_ipv6 = 1
EOF

### disable some services
CHKCONFIG_OFF="firstboot cpuspeed lvm2-monitor kudzu isdn ip6tables auditd restorecond atd readahead_early mcstrans \
setroubleshoot portmap nfslock mdmonitor rpcidmapd rpcgssd bluetooth pcscd apmd hidd autofs cups gpm xfs anacron rhnsd \
yum-updatesd avahi-daemon netfs iscsid iscsi rawdevices netfs abrtd kdump"
for s in $CHKCONFIG_OFF; do
[ -f "/etc/init.d/$s" ] && chkconfig $s off
done

CHKCONFIG_ON="iptables ntpd rsyslog"
for s in $CHKCONFIG_ON; do
[ -f "/etc/init.d/$s" ] && chkconfig $s on
done

#disable ntpd on paravirtualized XEN-DOMU
[ "$VIRTUAL" = "XEN-DOMU" ] && { echo -e '\n#unlink dom0 and domU clock to work ntpd\nxen.independent_wallclock = 1' \
>> /etc/sysctl.conf; }

#disable smartd on virtual machines
[ -n "$VIRTUAL"  ] && [ -f "/etc/init.d/smartd" ] && chkconfig smartd off

# tune bash
echo 'HISTCONTROL=ignoreboth' >> /etc/profile
sed -i 's|^HISTSIZE=.*|HISTSIZE=1000000|' /etc/profile

# enable sudo for wheel and requretty
sed 's|^# %wheel\tALL=(ALL)\tALL|%wheel\tALL=(ALL)\tALL|; s|^Defaults    requiretty|#&|' -i /etc/sudoers
sed 's|^# %wheel\tALL=(ALL)\tNOPASSWD: ALL|%wheel\tALL=(ALL)\tNOPASSWD: ALL|; s|^Defaults    requiretty|#&|' -i /etc/sudoers

# tune iptables
cat << EOF > /etc/sysconfig/iptables
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT

*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
COMMIT

*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]

-A INPUT -p ICMP --icmp-type timestamp-request -j DROP
-A OUTPUT -p ICMP --icmp-type timestamp-reply -j DROP

COMMIT

*raw
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A PREROUTING -j NOTRACK
-A OUTPUT -j NOTRACK
COMMIT

EOF

### ENVDEV-1348. Do not format!!!

echo '*** /usr/lib/rpm/rpmpopt-4.4.2.3 2009-07-24 09:56:42.000000000 +0400
--- /etc/popt   2010-02-10 14:52:56.000000000 +0300
***************
*** 78,83 ****
--- 78,84 ----
  %|PACKAGER?{Packager    : %{PACKAGER}\n}|\
  %|URL?{URL         : %{URL}\n}|\
  Summary     : %{SUMMARY}\n\
+ Arch: %{ARCH}\n\
  Description :\n%{DESCRIPTION}\n'\'' \
        --POPTdesc=$"list descriptive information from package(s)"
 
***************
*** 361,366 ****
--- 362,368 ----
  %|PACKAGER?{Packager    : %{PACKAGER}\n}|\
  %|URL?{URL         : %{URL}\n}|\
  Summary     : %{SUMMARY}\n\
+ Arch: %{ARCH}\n\
  Description :\n%{DESCRIPTION}\n'\'' \
        --POPTdesc=$"list descriptive information from package(s)"' | patch -o /etc/popt /usr/lib/rpm/rpmpopt-4.4.2.3 > /dev/null && chmod 644 /etc/popt
# noclear console 
sed -i 's|^1:2345:respawn:/sbin/mingetty tty1|1:2345:respawn:/sbin/mingetty --noclear tty1|' /etc/inittab


[ -f "/etc/sysconfig/prelink" ] && sed -i 's|^PRELINKING=yes$|PRELINKING=no|' /etc/sysconfig/prelink

### bug with disable selinux in install section
[ -f "/etc/selinux/config" ] && sed 's|^SELINUX=.*|SELINUX=disabled|' -i /etc/selinux/config

### disable all external yum repos
find /etc/yum.repos.d/ -mindepth 1 -name \*.repo -exec sed 's|^[^#].\+|#&|g' -i '{}' +
# temporary yum repo

cat << EOF >> /etc/yum.repos.d/phorm-tmp.repo

[phorm-os]
name=phorm/production-cn-ccap/AdServer/os
baseurl=http://repo.cn10.phorm.com/repos/production-cn-ccap/AdServer/RPMS.os
enabled=1

[phorm-updates]
name=phorm/production-cn-ccap/AdServer/updates
baseurl=http://repo.cn10.phorm.com/repos/production-cn-ccap/AdServer/RPMS.updates
enabled=1

[phorm-cms]
name=phorm/production-cn-ccap/AdServer/cms
baseurl=http://repo.cn10.phorm.com/repos/production-cn-ccap/AdServer/RPMS.cms
enabled=1

[phorm-common]
name=phorm/production-cn-ccap/AdServer/common
baseurl=http://repo.cn10.phorm.com/repos/production-cn-ccap/AdServer/RPMS.common
enabled=1

[phorm-phorm]
name=phorm/production-cn-ccap/AdServer/phorm
baseurl=http://repo.cn10.phorm.com/repos/production-cn-ccap/AdServer/RPMS.phorm
enabled=1

EOF

yum --quiet --noplugins --nogpgcheck --disablerepo=phorm-cms,phorm-common install python-hashlib -y
yum --quiet --noplugins --nogpgcheck install apt -y

### install host configuration package
yum -y --quiet --nogpgcheck install ks-host-production-cn-ccap && rm -f /etc/yum.repos.d/phorm-tmp.repo
yum -y --quiet remove net-snmp-libs.i386
yum -y --quiet install kernel-uek.x86_64

## Disable interactive prompt menu
sed -i 's|PROMPT=yes|PROMPT=no|' /etc/sysconfig/init

sed -i 's|^timeout=.*|timeout=120|' /boot/grub/grub.conf
sed -i 's|^default=.*|default=0|' /boot/grub/grub.conf

echo "
title PXE Boot
        root (hd0,0)
        kernel /boot/6.5.vmlinuz ksdevice=eth0 text gateway=10.122.76.1 netmask=255.255.255.0 method=http://10.122.76.252/CentOS/6.5/os/x86_64 nameserver=10.122.76.252 ks=http://10.122.76.252/netboot/kickstart/kickstart-cn10proadbe01 ip=10.122.76.244
        initrd /boot/6.5.initrd.img
" >> /boot/grub/grub.conf

wget http://10.122.76.252/CentOS/6.5/os/x86_64/images/pxeboot/initrd.img -O /boot/6.5.initrd.img
wget http://10.122.76.252/CentOS/6.5/os/x86_64/images/pxeboot/vmlinuz -O /boot/6.5.vmlinuz

### Monitoring
sed 's|^SYSLOGD_OPTIONS=.*|SYSLOGD_OPTIONS="-c3"|' -i /etc/sysconfig/rsyslog
#sed -e 's|^$ModLoad imklog.*|#&|g' -e '1i $ModLoad imklog' -e '1i $ModLoad imuxsock' -i /etc/rsyslog.conf

sed '/^$ModLoad imuxsock/a *.warn                                                  @zenoss:2514 \
:programname, startswith, "OIX" ~' -i /etc/rsyslog.conf
   

### Install snmpd

yum --quiet install net-snmp-subagent -y


groupadd -f -g 506 adgroup 1>/dev/null ||:
# create snmp config
mv -f /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf.dist

echo 'com2sec         notConfigUser  default       V9AaE_3G+2-0
group           notConfigGroup v1            notConfigUser
group           notConfigGroup v2c           notConfigUser
access          notConfigGroup ""            any  noauth exact systemview none none

view            systemview     included      .1
#for hight load system comment the line above and uncomment below
#this will exclude large tcp connection tables from default system view
#view    systemview    included   .1.3.6.1.2.1.1
#view    systemview    included   .1.3.6.1.2.1.2
#view    systemview    included   .1.3.6.1.2.1.4
#view    systemview    included   .1.3.6.1.2.1.25
#view    systemview    included   .1.3.6.1.2.1.31
#view    systemview    included   .1.3.6.1.4.1.777
#view    systemview    included   .1.3.6.1.4.1.2021
#view    systemview    included   .1.3.6.1.4.1.28675
#view    systemview    included   .1.3.6.1.4.1.57052



master  agentx
agentxperms 770 770 daemon adgroup

dontLogTCPWrappersConnects 1
interface lo 24 1000000000' > /etc/snmp/snmpd.conf

sed 's|\(syslocation[^.]\+\)\..*$|\1|' -i /etc/snmp/snmpd.conf
echo 'OPTIONS="-Lsd -Lf /dev/null -p /var/run/snmpd.pid"' >> /etc/sysconfig/snmpd.options

service snmpd start > /dev/null && chkconfig snmpd on && sleep 3
chown daemon.adgroup /var/agentx


# install other packages

yum --quiet install noc-usermgr-server screen apt -y
wget http://10.122.76.252/ssl.tbz -O /tmp/ssl.tbz
wget http://10.122.76.252/userupdate.conf -O /opt/noc/usermgr/server/userupdate.conf
chmod 644 /opt/noc/usermgr/server/userupdate.conf
cd /opt/noc/; tar -jxf /tmp/ssl.tbz; rm -f /tmp/ssl.tbz

# upgrade all packages

yum --quiet upgrade -y

##parameters for KVM kernel
[ "$VIRTUAL" = "KVM" ] && { sed -i 's|\(.*/vmlinuz-.*\)|\1 divider=10 clocksource=acpi_pm console=tty0 console=ttyS0,115200|' /boot/grub/grub.conf; }
[ "$VIRTUAL" = "KVM" ] && { echo -e "serial --unit=0 --speed=115200\nterminal --timeout=5 serial console" >> /boot/grub/grub.conf; }

##prepare root .ssh dir
mkdir --mode=700 ~root/.ssh && touch ~root/.ssh/authorized_keys && chmod 600 ~root/.ssh/authorized_keys

adduser ivan.vinitskyy -u 502 -g users -G wheel -p '$1$EiAarB8K$..J3fcVEU.MA6CBdHhvQK1'
sudo -u ivan.vinitskyy  mkdir --mode=700 ~ivan.vinitskyy/.ssh
[ ! -f ~ivan.vinitskyy/.ssh/authorized_keys ] && echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA0qKvNvSw8ftyF9CnoHQISesOVcJROhg9RUbLCmCdphC87sTY4eLDUcP/K1hioDFL17MRewhBcfTETtjz+uXyB+5LUHh1dzPp+jw13JC1iJQEGy+lIONUlr8JLY4Uud6fDe24uwgEfQKZPRKeoAxsehjc6zgvq+jiM6yRHZg9kNaY+w69okcgw1qWUFvNCtamdK2LJFdqelwkxtuTeb+w/wyTqOMhkVZvDXw33/tHwwkurk2phjH4r/sJJcUgmjzEJfl8XdkhMxqbLY0ZU4UXB23mpd4OOQffsQeOMrNJ5wMyWsbOXVZCEh2xFB5nfIXzQhvfoO0Zitx65gixclgvvQ== ivan.vinitskyy@phorm.com' | sudo -u ivan.vinitskyy -H bash -c 'cat >> ~ivan.vinitskyy/.ssh/authorized_keys'
chmod 600 ~ivan.vinitskyy/.ssh/authorized_keys

adduser olgierd.ziolko -u 503 -g users -G wheel -p '$1$hnPhDNrF$APd7gXG/1bTa2dgO5xy93.'
sudo -u olgierd.ziolko  mkdir --mode=700 ~olgierd.ziolko/.ssh
[ ! -f ~olgierd.ziolko/.ssh/authorized_keys ] && echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAprt0/lL+3zQP4OtO51cpyVGeLK00CxY8o8cxgv9XfXNux+liRysEiH5bqu8x/e9KiigHig+2+76kE2tSEvZZ/06lnvel2jWngWMjvt5Glv4co2LfXMT1+ZvRRc/IJ/iKi41oCrcB3MCKi9vUnzk/mjBV4Ysljwgy6rg+ZkoKWZs= olgierd@phorm-20121001' | sudo -u olgierd.ziolko -H bash -c 'cat >> ~olgierd.ziolko/.ssh/authorized_keys'
chmod 600 ~olgierd.ziolko/.ssh/authorized_keys

adduser tibor.racz -u 1030 -g users -G wheel -p '$1$JNwFDHj8$YVIxYFvRxij90xy.7YBpn/'
sudo -u tibor.racz  mkdir --mode=700 ~tibor.racz/.ssh
[ ! -f ~tibor.racz/.ssh/authorized_keys ] && echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQACbaQ4Kvbe7EqzS0vlSNViOdOPqgDLHVZ2r3ssrqe46aZW189yjw2nlQ5bQpnGm/zvurMx5EN3JYvIyG0rtAEnEzMYThoykiRDgzH8JIs6OSAznJ0eNhjbpPLf/U6F6G0dWTmSD8FGvIurbDknjBRMGcxlZH3MsXbTdRw6wmK4IBX5ElaXvJU8nGqdBJG4qHeqNOhi6gzqJrURoijTtmWTFzkE+NjJDmxFuayV9FuI8N5z6TuNDiD+IIJjq5kLfPl1AKIpijhenqT7MK+CGKVbd9nqmoyaEO3Gm2OPQGinKUPHfggKGII71UOeGzCouRYoKQfBHzo+zs0Zgs3fq3 Tibor' | sudo -u tibor.racz -H bash -c 'cat >> ~tibor.racz/.ssh/authorized_keys'
chmod 600 ~tibor.racz/.ssh/authorized_keys

adduser sergey.filippov -u 530 -g users -G wheel -p '$1$8SFez2RL$sgsdBywQBIuqxhZFmbNxo0'
sudo -u sergey.filippov  mkdir --mode=700 ~sergey.filippov/.ssh
[ ! -f ~sergey.filippov/.ssh/authorized_keys ] && echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA7gGVIpvqolFFnSihnNGLwJMAtTSF4vynNXInwrjhNZn13Wa2kDU4Q5i+SNvOtc2wDjL+qqddxeHV/OAOI04rp0fJBGkRYls3cNc6MQVnynTQ2BvnVSR8ulsPdMqpkdNBnwnX1eqpjvLF6z8978dRU0A5lfNuu2T9o+REelsTJPmQS8qCqcH9YsVx2dGsrHTlFEeeuGDSqqpriTrLlwGTjNF28OLRDzqeXqQrm+qpLfzg5abyoBgtWFETZTGMpqgmlyA9FjsCejEjQIWFpcEOx7AjogFjSiompLYIoOkiAWOffSRgpDAXIkPmzvCq/muu/krWhbEcMvOE1HHvSgf0Qw== antifreeze@sfilippov' | sudo -u sergey.filippov -H bash -c 'cat >> ~sergey.filippov/.ssh/authorized_keys'
chmod 600 ~sergey.filippov/.ssh/authorized_keys

adduser steve.cherry -u 669 -g users -G wheel -p '$1$7WUNydWm$8fNZQn3fYRevqHpD4m5dp.'
sudo -u steve.cherry  mkdir --mode=700 ~steve.cherry/.ssh
[ ! -f ~steve.cherry/.ssh/authorized_keys ] && echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC28UOD1KYkcoV7zIDXOzGRLOo7vhNKYdfrE1CrTU47lfztwafJVPe31dpt9jTQLYjaGDph8iyZnn/YCyfjSViy6qUxJnFp+oVRYyBEQhJwGgoweecY8rvXloCA8zluA9jYWJOiIBeLqjroR4huHHYhgeOUkjNK+xnEnUSog4Kle04SPyDh6UvoFp/KcdKs57RQp8JQNqWFcbQ4zWeQiJJW44PnnOrUpjkI6y6H2Xl6G2ECSn+74lnfNYugB05KuLuWykk0mxYiHVG3QhZ2KjsYKcRduRGOF8TKeJx2Oxc7PTp2egNi8Ry50rqKtdDoS2yri8LzCP4Rs1igP/rU/1Cn steve-cherry@steve' | sudo -u steve.cherry -H bash -c 'cat >> ~steve.cherry/.ssh/authorized_keys'
chmod 600 ~steve.cherry/.ssh/authorized_keys

adduser byron.sorgdrager -u 501 -g users -G wheel -p '$1$B22HwcPi$i0k106jdbjp6k.JcT7Kyu.'
sudo -u byron.sorgdrager  mkdir --mode=700 ~byron.sorgdrager/.ssh
[ ! -f ~byron.sorgdrager/.ssh/authorized_keys ] && echo 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAkaNLX1sgTvoHgLSImsD7RyD1qyEXTSbC74BimLY1arz4M+w5YlT44S9IrtBUWFZYhilI2FOoHSSD8bW0RybdKSItN1yCaSM2BmWNxxuunhAblDNnnzUaGbNZU9bXjLEeS292KBBTtG7f/mGFQaFpHRgCYyzAMxl1kd6EQSYHGDkdYwJpHHz23ItlQ0oEoWCsUdu2u1KoEWMRSZGrqpe0CAWke8GeIRn7jIw7PCs8VNfMvLV29MvKh9G426fESXie7XPJT3upGoEiaWDPHIQq5b6CZNSo9HKt+WZdgUY1t+DVzLGrALQBpY//kD7n9y60Xs2RQ0fgvX6WX97jyN/arQ== bs-key' | sudo -u byron.sorgdrager -H bash -c 'cat >> ~byron.sorgdrager/.ssh/authorized_keys'
chmod 600 ~byron.sorgdrager/.ssh/authorized_keys
cp ~byron.sorgdrager/.ssh/authorized_keys /var/lib/ssh_pubkeys/byron.sorgdrager.pub

chown root: /var/lib/ssh_pubkeys/*
chmod 644 /var/lib/ssh_pubkeys/*


groupadd -g 506 adgroup
adduser -u 506 -g adgroup aduser
sudo -u aduser mkdir --mode=700 ~aduser/.ssh

#send all root mail to admins
echo 'root:           noc@phorm.com' >> /etc/aliases

#additional postinstall
# This sets up dhclient for eth0 which is required for Huawei MGMT.
# PEERDNS=no means resolv.conf won't be updated
MAC=`grep HWADDR /etc/sysconfig/network-scripts/ifcfg-eth0 | cut -f2 -d'='`
cat >/etc/sysconfig/network-scripts/ifcfg-eth0 << EOC
DEVICE=eth0
BOOTPROTO=dhcp
HWADDR=${MAC}
ONBOOT=yes
PEERDNS=no
EOC

# Get proper XEN drivers which are from Huawei
#cd /tmp
#wget http://10.122.76.252/uvp-tools-linux-1.1.5.62.010-14.tar
#tar -xf uvp-tools-linux-1.1.5.62.010-14.tar

yum -y --quiet --noplugins --nogpgcheck install oix-server-remote oix-manager oix-server-remote-debuginfo oix-config-server-production-cn-ccap-local-mgr oix-config-server-production-cn-ccap oix-config-server-production-cn-ccap-mgr oix-dictionaries oix-polyglot-dict oix-pagesense-production-cn-ccap

# FIX FOR NOC-13240
host=`cat /etc/sysconfig/network | grep HOSTNAME |cut -f2 -d=`
if [ $host == 'cn10prolb00' -o $host == 'cn10prolb01' ]; then
        echo -e '#FIX FOR NOC-13240 START\n/usr/sbin/ethtool -K eth4 tx off\n/usr/sbin/ethtool -K eth3 tx off\n/usr/sbin/ethtool -K eth2 tx off\n/usr/sbin/ethtool -K eth1 tx off\n/usr/sbin/ethtool -K eth0 tx off\n#FIX FOR NOC-13240 END\n' >> /etc/rc.local
else
        echo -e '#FIX FOR NOC-13240 START\n/usr/sbin/ethtool -K eth1 tx off\n/usr/sbin/ethtool -K eth0 tx off\n#FIX FOR NOC-13240 END\n' >> /etc/rc.local
fi


# Remove nameserver resolution from eth0 which was needed only for kickstart
sed -i -e 's/nameserver 10.122.76.252//g' /etc/resolv.conf

# Since we needed only eth0 for kickstarting purposes we have change default gw to point to LB here, we grab it from route-eth1 since it will be correct one
# cn10procms00/lb00/lb01 should have 10.122.76.1 as default gateway
GOODGW=`grep GATEWAY /etc/sysconfig/network-scripts/route-eth1 | cut -f2 -d=`
if [ $host != 'cn10prolb00' -o $host != 'cn10prolb01' -o $host != 'cn10procms00' ]; then
        sed -i -e "s/GATEWAY.*/GATEWAY=${GOODGW}/" /etc/sysconfig/network
fi

# Disable networking for first boot so XEN drivers can be deployed succesfully
#/sbin/chkconfig --level 2345 network off

### FIRST BOOT
# Install Huawei drivers during first boot, enable networking, remove first boot script and reboot
#echo "cd /tmp/uvp-tools-linux-1.1.5.62.010-14; \
#./install -i; \
#depmod -ae; \
#/sbin/chkconfig --level 2345 network on; \
#sed -i -e 's/cd.*//g' /etc/rc.local; \
#reboot" >> /etc/rc.local

rm -f /etc/sysconfig/network-scripts/route-eth1
cd /etc/ssh/ ; tar -jxf /u01/ssh.tbz ; rm -f /u01/ssh.tbz

# send email

interface=`ip r | grep default | cut -f5 -d" "`
gateway=`ip r | grep default | cut -f3 -d" "`
ipaddress=`ifconfig $interface | grep 'inet addr' | sed 's|\:| |g' | awk '{print $3}'`
netmask=`ifconfig $interface | grep 'inet addr' | sed 's|\:| |g' | awk '{print $7}'`
macaddr=`ip a s $interface | grep 'link/ether' | awk '{print $2}'`
os=`cat /etc/redhat-release`
arch=`uname -m`
host=`cat /etc/sysconfig/network | grep HOSTNAME | cut -f 2 -d=`
dtae=`date +'%R %d/%m/%Y'`

echo "/opt/noc/usermgr/server/userUpdate.pl > /dev/null 2>&1" >> /etc/rc.local
echo "/opt/noc/usermgr/server/userUpdate.pl > /dev/null 2>&1" >> /etc/rc.local

### send mail of success
service postfix start > /dev/null

echo -e "date: ${dtae}\nipaddr: ${ipaddress}\nos: ${os}\narch: ${arch}\ninterface: ${interface}\nmac: ${macaddr}\nplatform: \
`dmidecode -s baseboard-manufacturer` `dmidecode -s baseboard-product-name`\nvirtual: ${VIRTUAL:-No}\n\n#free\n`free`\n\n\
#fdisk -l`fdisk -l`\n\n#lspci\n`lspci`\n\n# \
`awk -F': ' '/^model name/{mn=$2} /^physical id/{pi=$2} /^cpu cores/{cc=$2} /^flags/{f=$2} \
END{ printf("CPU info:\nname: %s\nCPU: %s physical * %s cores\nflags: %s\n", mn,pi+1,cc,f)}' /proc/cpuinfo`\n\n\
#Accounts , present on server:\n\n `cat /etc/passwd | grep /bin/bash | cut -d ':' -f 1`" \
| mail -s "INFO: new server ready.. [${host} ${ipaddress}/${macaddr}]" noc@phorm.com

sleep 10

exit
) 1>/root/post_install.log 2>&1