---
- hosts: new
  remote_user: ibmcloud
  sudo: yes
  gather_facts: true
  vars:
    user: ibmcloud
  tasks:
  - name: install provisioning tools, git and zsh dstat via yum
    yum: name={{ item }} state=installed
    when: ansible_os_family == "RedHat"
    with_items:
     - git
     - zsh
     - dstat
     - htop
     - screen
  - name: install provisioning tools, git and zsh dstat via apt-get
    apt: name={{ item }} state=installed
    when: ansible_os_family == "Debian"
    with_items:
     - git
     - zsh
     - dstat
     - htop
     - screen
  - name: install zsh as default shell
    script: /etc/ansible/setuptools/init_zsh.sh
  - name: copy default screen file
    copy: src=/etc/ansible/setuptools/screenrc dest=/etc/screenrc mode=0644 owner=root group=root
  - name: copy ssh provate key
    copy: src=/etc/ansible/setuptools/myprivate.pem dest=/home/{{user}}/.ssh/ mode=0600 owner={{user}} group={{user}}
  
